version: '3.8'
services:
  api:
    image: rub21/osm-sandbox-web:v6
    env_file:
      - ./.env
    build:
      context: ./images/web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    working_dir: /var/www
